<?php
/**
 * Created by PhpStorm.
 * User: Duck
 * Date: 2017-07-07
 * Time: 11:14
 */

namespace frontend\components;
use source\helpers\JSSDK;
use yii\base\Widget;

class ShareWechat extends Widget{
    public $title;
    public $image;
    public $url;
    public $describe;
    public function init()
    {
        if($this->title===null){
            $this->title='';
        }
        if($this->describe===null){
            $this->describe='';
        }
        if($this->url===null){
            $this->url='';
        }
        if($this->image===null){
            $this->image='';
        }
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
	    $appid = \yii::$app->params['appid'];//微信的配置文件
	    $appsecret = \yii::$app->params['appsecret'];//微信的配置文件

        $jssdk = new JSSDK($appid,$appsecret);
	    $configShare = $jssdk->getSignPackage();

	    $share = [
		    'checkJsApi',
		    'onMenuShareTimeline',
		    'onMenuShareAppMessage',
		    'onMenuShareQQ',
		    'onMenuShareWeibo',
		    'onMenuShareQZone',
		    'hideMenuItems',
		    'showMenuItems',
		    'hideAllNonBaseMenuItem',
		    'showAllNonBaseMenuItem',
		    'translateVoice',
		    'startRecord',
		    'stopRecord',
		    'onVoiceRecordEnd',
		    'playVoice',
		    'onVoicePlayEnd',
		    'pauseVoice',
		    'stopVoice',
		    'uploadVoice',
		    'downloadVoice',
		    'chooseImage',
		    'previewImage',
		    'uploadImage',
		    'downloadImage',
		    'getNetworkType',
		    'openLocation',
		    'getLocation',
		    'hideOptionMenu',
		    'showOptionMenu',
		    'closeWindow',
		    'scanQRCode',
		    'chooseWXPay',
		    'openProductSpecificView',
		    'addCard',
		    'chooseCard',
		    'openCard'
	    ];
        //渲染
        return $this->render('sharewx',[
            'title'=>$this->title,
            'image'=>$this->image,
            'url'=>$this->url,
            'describe'=>$this->describe,
            'configShare'=>$configShare,
	        'share'=>$share
        ]);
        parent::run(); // TODO: Change the autogenerated stub
    }

}